version: '3'

services:
    app:
        build: .
        container_name: bankroll_management_php
        volumes:
            - .:/var/www
            - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - app-network
        depends_on:
            - db

    nginx:
        build: .docker/nginx
        container_name: bankroll_management_nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    db:
        build: ./.docker/postgres
        container_name: bankroll_management_database
        restart: always
        tty: true
        ports:
            - "5432:5432"
        volumes:
            - ./.docker/dbdata:/data/postgres
            - ./.docker/postgres:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=bankroll_management
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
