version: '3.8'

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: bankroll-management-php
        image: bankroll-management/php
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - bankroll-management-php
    
    nginx:
        image: nginx:latest
        container_name: bankroll-management-nginx
        ports:
            - 8888:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - bankroll-management-php

networks:
    bankroll-management-php:
        driver: bridge